"""
Background Service Setup Wizard
Easy interactive setup for background blog publishing
"""
import os
import sys
from pathlib import Path

def clear_screen():
    """Clear the console screen"""
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*80)
    print(text.center(80))
    print("="*80 + "\n")

def setup_blog_config():
    """Set up blog configuration"""
    print_header("STEP 1: BLOG CONFIGURATION")

    print("Let's find your blog...")

    try:
        from src.blogger_publisher import BloggerPublisher

        publisher = BloggerPublisher()
        print("✅ Authenticating with Blogger...")
        publisher.authenticate()

        blogs = publisher.get_blogs()

        if not blogs:
            print("❌ No blogs found. Please create a blog at blogger.com first.")
            return None

        print(f"\n📚 Found {len(blogs)} blog(s):\n")
        for i, blog in enumerate(blogs, 1):
            print(f"  {i}. {blog['name']}")
            print(f"     URL: {blog['url']}")
            print(f"     ID: {blog['id']}\n")

        if len(blogs) == 1:
            selected_blog = blogs[0]
            print(f"✅ Using blog: {selected_blog['name']}")
        else:
            while True:
                try:
                    choice = int(input(f"Select blog (1-{len(blogs)}): "))
                    if 1 <= choice <= len(blogs):
                        selected_blog = blogs[choice - 1]
                        break
                    else:
                        print("❌ Invalid choice. Try again.")
                except ValueError:
                    print("❌ Please enter a number.")

        # Save blog ID
        blog_id = selected_blog['id']
        with open('blog_config.txt', 'w') as f:
            f.write(blog_id)

        print(f"\n✅ Configuration saved!")
        print(f"   Blog: {selected_blog['name']}")
        print(f"   ID: {blog_id}")

        return blog_id

    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return None

def setup_schedule():
    """Configure schedule time"""
    print_header("STEP 2: SCHEDULE CONFIGURATION")

    print("When should blog posts be published daily?\n")
    print("Examples:")
    print("  09:00 - 9:00 AM")
    print("  14:30 - 2:30 PM")
    print("  20:00 - 8:00 PM")

    while True:
        time_str = input("\nEnter time (HH:MM in 24-hour format): ").strip()

        if not time_str:
            time_str = "09:00"

        # Validate format
        try:
            hours, minutes = time_str.split(':')
            hours = int(hours)
            minutes = int(minutes)

            if 0 <= hours <= 23 and 0 <= minutes <= 59:
                print(f"\n✅ Scheduled for: {time_str} daily")
                return time_str
            else:
                print("❌ Invalid time. Hours must be 0-23, minutes 0-59.")
        except:
            print("❌ Invalid format. Use HH:MM (e.g., 09:00)")

def setup_post_count():
    """Configure number of posts"""
    print_header("STEP 3: POST VOLUME")

    print("How many posts should be published per day?\n")
    print("Recommendations:")
    print("  3-5 posts  - Good starting point")
    print("  5-10 posts - Aggressive growth")
    print("  10+ posts  - Maximum coverage")

    while True:
        try:
            num_posts = input("\nEnter number of posts (default: 5): ").strip()

            if not num_posts:
                num_posts = 5
            else:
                num_posts = int(num_posts)

            if 1 <= num_posts <= 20:
                print(f"\n✅ Will publish {num_posts} posts per day")
                return num_posts
            else:
                print("❌ Please enter a number between 1 and 20.")
        except ValueError:
            print("❌ Please enter a valid number.")

def create_env_file(blog_id, schedule_time, num_posts):
    """Create .env file with configuration"""
    env_content = f"""# Automated Blogger Configuration
# Generated by setup wizard

# Blog Configuration
BLOGGER_BLOG_ID={blog_id}

# Schedule Configuration
BLOGGER_SCHEDULE_TIME={schedule_time}
BLOGGER_NUM_POSTS={num_posts}

# API Keys (if not already set)
# ANTHROPIC_API_KEY=your_key_here
# OPENAI_API_KEY=your_key_here
"""

    with open('.env', 'a') as f:
        f.write('\n' + env_content)

    print("✅ Configuration saved to .env file")

def test_service():
    """Test the service"""
    print_header("STEP 4: TEST SERVICE")

    print("Let's test if everything is working...\n")

    response = input("Do you want to run a test now? (y/n): ").strip().lower()

    if response == 'y':
        print("\n🧪 Running test (this may take 2-3 minutes)...\n")

        try:
            from trending_blogger import TrendingBlogger

            # Get blog ID
            with open('blog_config.txt', 'r') as f:
                blog_id = f.read().strip()

            # Initialize
            blogger = TrendingBlogger(blog_id=blog_id)

            print("🔍 Finding trending topics...")
            topics = blogger.trending_finder.get_all_trending_topics()

            if topics:
                print(f"✅ Found {len(topics)} trending topics!")
                print("\n📋 Sample topics:")
                for i, topic in enumerate(topics[:3], 1):
                    print(f"  {i}. {topic[:70]}...")

                # Test generation (without publishing)
                print("\n✅ Service test successful!")
                print("   All components are working correctly.")
            else:
                print("⚠️  No trending topics found, but service is working.")
                print("   (May be network issue or rate limiting)")

        except Exception as e:
            print(f"❌ Test failed: {str(e)}")
            print("\n⚠️  You may need to:")
            print("   1. Check your internet connection")
            print("   2. Verify API credentials")
            print("   3. Re-authenticate with Blogger")

    else:
        print("\n⏭️  Skipping test. You can test later manually.")

def setup_autostart():
    """Configure Windows auto-start"""
    print_header("STEP 5: AUTO-START ON BOOT")

    print("Would you like the service to start automatically when Windows boots?\n")

    response = input("Enable auto-start? (y/n): ").strip().lower()

    if response == 'y':
        print("\n📋 To enable auto-start:")
        print("\n  Option 1: Task Scheduler (Recommended)")
        print("    1. Press Win+R, type: taskschd.msc")
        print("    2. Create Basic Task")
        print("    3. Name: Automated Blogger")
        print("    4. Trigger: At startup")
        print("    5. Action: Start a program")
        print("    6. Program: pythonw.exe")
        print(f"    7. Arguments: \"{Path.cwd() / 'trending_blogger_background.py'}\"")
        print(f"    8. Start in: \"{Path.cwd()}\"")
        print("\n  See BACKGROUND_SERVICE.md for detailed instructions.")

        input("\nPress Enter to continue...")
    else:
        print("\n⏭️  Auto-start not enabled.")
        print("   You can enable it later using Task Scheduler.")

def main():
    """Main setup wizard"""
    clear_screen()

    print("="*80)
    print("🚀 AUTOMATED TRENDING BLOGGER - BACKGROUND SERVICE SETUP".center(80))
    print("="*80)
    print("\n   This wizard will help you set up automated blog publishing")
    print("   that runs in the background 24/7.\n")

    input("Press Enter to start...")

    # Step 1: Blog configuration
    blog_id = setup_blog_config()
    if not blog_id:
        print("\n❌ Setup failed. Please try again.")
        return

    input("\nPress Enter to continue...")
    clear_screen()

    # Step 2: Schedule
    schedule_time = setup_schedule()

    input("\nPress Enter to continue...")
    clear_screen()

    # Step 3: Post count
    num_posts = setup_post_count()

    # Step 4: Create env file
    create_env_file(blog_id, schedule_time, num_posts)

    input("\nPress Enter to continue...")
    clear_screen()

    # Step 5: Test service
    test_service()

    input("\nPress Enter to continue...")
    clear_screen()

    # Step 6: Auto-start
    setup_autostart()

    # Final summary
    clear_screen()
    print_header("✅ SETUP COMPLETE!")

    print("Your automated blogger is configured and ready to run!\n")
    print("📊 Configuration Summary:")
    print(f"   • Blog ID: {blog_id}")
    print(f"   • Schedule: {schedule_time} daily")
    print(f"   • Posts per day: {num_posts}")
    print(f"   • Configuration: blog_config.txt")

    print("\n🚀 To start the background service:\n")
    print("   Method 1: Double-click 'start_background_trending.bat'")
    print("   Method 2: Run 'python run_background.py'")
    print("   Method 3: Use Task Scheduler (see BACKGROUND_SERVICE.md)")

    print("\n📖 Documentation:")
    print("   • BACKGROUND_SERVICE.md - Complete background service guide")
    print("   • TRENDING_TOPICS.md - Trending topics features")
    print("   • WHICH_BLOGGER_TO_USE.md - Comparison guide")

    print("\n📝 Logs will be saved to:")
    print("   • logs/background_service.log")
    print("   • logs/app.log")

    print("\n" + "="*80)
    print("Happy automated blogging! 🎉".center(80))
    print("="*80 + "\n")

if __name__ == "__main__":
    main()
